// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: workqueue/v1/query.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryWorkRequest is the request for querying a specific work unit
type QueryWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWorkRequest) Reset() {
	*x = QueryWorkRequest{}
	mi := &file_workqueue_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWorkRequest) ProtoMessage() {}

func (x *QueryWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWorkRequest.ProtoReflect.Descriptor instead.
func (*QueryWorkRequest) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryWorkRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

// QueryWorkResponse is the response for querying a specific work unit
type QueryWorkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Work is the requested work unit
	Work          *WorkUnit `protobuf:"bytes,1,opt,name=work,proto3" json:"work,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWorkResponse) Reset() {
	*x = QueryWorkResponse{}
	mi := &file_workqueue_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWorkResponse) ProtoMessage() {}

func (x *QueryWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWorkResponse.ProtoReflect.Descriptor instead.
func (*QueryWorkResponse) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryWorkResponse) GetWork() *WorkUnit {
	if x != nil {
		return x.Work
	}
	return nil
}

// QueryPendingWorkRequest is the request for querying pending work
type QueryPendingWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPendingWorkRequest) Reset() {
	*x = QueryPendingWorkRequest{}
	mi := &file_workqueue_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPendingWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPendingWorkRequest) ProtoMessage() {}

func (x *QueryPendingWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPendingWorkRequest.ProtoReflect.Descriptor instead.
func (*QueryPendingWorkRequest) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_query_proto_rawDescGZIP(), []int{2}
}

// QueryPendingWorkResponse is the response for querying pending work
type QueryPendingWorkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PendingWork is the list of pending work units
	PendingWork   []*WorkUnit `protobuf:"bytes,1,rep,name=pending_work,json=pendingWork,proto3" json:"pending_work,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPendingWorkResponse) Reset() {
	*x = QueryPendingWorkResponse{}
	mi := &file_workqueue_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPendingWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPendingWorkResponse) ProtoMessage() {}

func (x *QueryPendingWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPendingWorkResponse.ProtoReflect.Descriptor instead.
func (*QueryPendingWorkResponse) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryPendingWorkResponse) GetPendingWork() []*WorkUnit {
	if x != nil {
		return x.PendingWork
	}
	return nil
}

// QueryValidatorStatsRequest is the request for querying validator stats
type QueryValidatorStatsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ValidatorAddress string                 `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryValidatorStatsRequest) Reset() {
	*x = QueryValidatorStatsRequest{}
	mi := &file_workqueue_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryValidatorStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryValidatorStatsRequest) ProtoMessage() {}

func (x *QueryValidatorStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryValidatorStatsRequest.ProtoReflect.Descriptor instead.
func (*QueryValidatorStatsRequest) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryValidatorStatsRequest) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

// QueryValidatorStatsResponse is the response for querying validator stats
type QueryValidatorStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stats contains the validator's statistics
	Stats         *ValidatorStats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryValidatorStatsResponse) Reset() {
	*x = QueryValidatorStatsResponse{}
	mi := &file_workqueue_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryValidatorStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryValidatorStatsResponse) ProtoMessage() {}

func (x *QueryValidatorStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryValidatorStatsResponse.ProtoReflect.Descriptor instead.
func (*QueryValidatorStatsResponse) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryValidatorStatsResponse) GetStats() *ValidatorStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// QueryTotalStatsRequest is the request for querying total statistics
type QueryTotalStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTotalStatsRequest) Reset() {
	*x = QueryTotalStatsRequest{}
	mi := &file_workqueue_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTotalStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTotalStatsRequest) ProtoMessage() {}

func (x *QueryTotalStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTotalStatsRequest.ProtoReflect.Descriptor instead.
func (*QueryTotalStatsRequest) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_query_proto_rawDescGZIP(), []int{6}
}

// QueryTotalStatsResponse is the response for querying total statistics
type QueryTotalStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TotalSubmitted is the total number of submitted work units
	TotalSubmitted uint64 `protobuf:"varint,1,opt,name=total_submitted,json=totalSubmitted,proto3" json:"total_submitted,omitempty"`
	// TotalValidated is the total number of validated work units
	TotalValidated uint64 `protobuf:"varint,2,opt,name=total_validated,json=totalValidated,proto3" json:"total_validated,omitempty"`
	// TotalRejected is the total number of rejected work units
	TotalRejected uint64 `protobuf:"varint,3,opt,name=total_rejected,json=totalRejected,proto3" json:"total_rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTotalStatsResponse) Reset() {
	*x = QueryTotalStatsResponse{}
	mi := &file_workqueue_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTotalStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTotalStatsResponse) ProtoMessage() {}

func (x *QueryTotalStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTotalStatsResponse.ProtoReflect.Descriptor instead.
func (*QueryTotalStatsResponse) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryTotalStatsResponse) GetTotalSubmitted() uint64 {
	if x != nil {
		return x.TotalSubmitted
	}
	return 0
}

func (x *QueryTotalStatsResponse) GetTotalValidated() uint64 {
	if x != nil {
		return x.TotalValidated
	}
	return 0
}

func (x *QueryTotalStatsResponse) GetTotalRejected() uint64 {
	if x != nil {
		return x.TotalRejected
	}
	return 0
}

var File_workqueue_v1_query_proto protoreflect.FileDescriptor

const file_workqueue_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x18workqueue/v1/query.proto\x12\x13pickle.workqueue.v1\x1a\x1cworkqueue/v1/workqueue.proto\"+\n" +
	"\x10QueryWorkRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\"F\n" +
	"\x11QueryWorkResponse\x121\n" +
	"\x04work\x18\x01 \x01(\v2\x1d.pickle.workqueue.v1.WorkUnitR\x04work\"\x19\n" +
	"\x17QueryPendingWorkRequest\"\\\n" +
	"\x18QueryPendingWorkResponse\x12@\n" +
	"\fpending_work\x18\x01 \x03(\v2\x1d.pickle.workqueue.v1.WorkUnitR\vpendingWork\"I\n" +
	"\x1aQueryValidatorStatsRequest\x12+\n" +
	"\x11validator_address\x18\x01 \x01(\tR\x10validatorAddress\"X\n" +
	"\x1bQueryValidatorStatsResponse\x129\n" +
	"\x05stats\x18\x01 \x01(\v2#.pickle.workqueue.v1.ValidatorStatsR\x05stats\"\x18\n" +
	"\x16QueryTotalStatsRequest\"\x92\x01\n" +
	"\x17QueryTotalStatsResponse\x12'\n" +
	"\x0ftotal_submitted\x18\x01 \x01(\x04R\x0etotalSubmitted\x12'\n" +
	"\x0ftotal_validated\x18\x02 \x01(\x04R\x0etotalValidated\x12%\n" +
	"\x0etotal_rejected\x18\x03 \x01(\x04R\rtotalRejected2\xa8\x03\n" +
	"\x05Query\x12U\n" +
	"\x04Work\x12%.pickle.workqueue.v1.QueryWorkRequest\x1a&.pickle.workqueue.v1.QueryWorkResponse\x12j\n" +
	"\vPendingWork\x12,.pickle.workqueue.v1.QueryPendingWorkRequest\x1a-.pickle.workqueue.v1.QueryPendingWorkResponse\x12s\n" +
	"\x0eValidatorStats\x12/.pickle.workqueue.v1.QueryValidatorStatsRequest\x1a0.pickle.workqueue.v1.QueryValidatorStatsResponse\x12g\n" +
	"\n" +
	"TotalStats\x12+.pickle.workqueue.v1.QueryTotalStatsRequest\x1a,.pickle.workqueue.v1.QueryTotalStatsResponseB-Z+github.com/maco144/pickle/x/workqueue/typesb\x06proto3"

var (
	file_workqueue_v1_query_proto_rawDescOnce sync.Once
	file_workqueue_v1_query_proto_rawDescData []byte
)

func file_workqueue_v1_query_proto_rawDescGZIP() []byte {
	file_workqueue_v1_query_proto_rawDescOnce.Do(func() {
		file_workqueue_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workqueue_v1_query_proto_rawDesc), len(file_workqueue_v1_query_proto_rawDesc)))
	})
	return file_workqueue_v1_query_proto_rawDescData
}

var file_workqueue_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_workqueue_v1_query_proto_goTypes = []any{
	(*QueryWorkRequest)(nil),            // 0: pickle.workqueue.v1.QueryWorkRequest
	(*QueryWorkResponse)(nil),           // 1: pickle.workqueue.v1.QueryWorkResponse
	(*QueryPendingWorkRequest)(nil),     // 2: pickle.workqueue.v1.QueryPendingWorkRequest
	(*QueryPendingWorkResponse)(nil),    // 3: pickle.workqueue.v1.QueryPendingWorkResponse
	(*QueryValidatorStatsRequest)(nil),  // 4: pickle.workqueue.v1.QueryValidatorStatsRequest
	(*QueryValidatorStatsResponse)(nil), // 5: pickle.workqueue.v1.QueryValidatorStatsResponse
	(*QueryTotalStatsRequest)(nil),      // 6: pickle.workqueue.v1.QueryTotalStatsRequest
	(*QueryTotalStatsResponse)(nil),     // 7: pickle.workqueue.v1.QueryTotalStatsResponse
	(*WorkUnit)(nil),                    // 8: pickle.workqueue.v1.WorkUnit
	(*ValidatorStats)(nil),              // 9: pickle.workqueue.v1.ValidatorStats
}
var file_workqueue_v1_query_proto_depIdxs = []int32{
	8, // 0: pickle.workqueue.v1.QueryWorkResponse.work:type_name -> pickle.workqueue.v1.WorkUnit
	8, // 1: pickle.workqueue.v1.QueryPendingWorkResponse.pending_work:type_name -> pickle.workqueue.v1.WorkUnit
	9, // 2: pickle.workqueue.v1.QueryValidatorStatsResponse.stats:type_name -> pickle.workqueue.v1.ValidatorStats
	0, // 3: pickle.workqueue.v1.Query.Work:input_type -> pickle.workqueue.v1.QueryWorkRequest
	2, // 4: pickle.workqueue.v1.Query.PendingWork:input_type -> pickle.workqueue.v1.QueryPendingWorkRequest
	4, // 5: pickle.workqueue.v1.Query.ValidatorStats:input_type -> pickle.workqueue.v1.QueryValidatorStatsRequest
	6, // 6: pickle.workqueue.v1.Query.TotalStats:input_type -> pickle.workqueue.v1.QueryTotalStatsRequest
	1, // 7: pickle.workqueue.v1.Query.Work:output_type -> pickle.workqueue.v1.QueryWorkResponse
	3, // 8: pickle.workqueue.v1.Query.PendingWork:output_type -> pickle.workqueue.v1.QueryPendingWorkResponse
	5, // 9: pickle.workqueue.v1.Query.ValidatorStats:output_type -> pickle.workqueue.v1.QueryValidatorStatsResponse
	7, // 10: pickle.workqueue.v1.Query.TotalStats:output_type -> pickle.workqueue.v1.QueryTotalStatsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_workqueue_v1_query_proto_init() }
func file_workqueue_v1_query_proto_init() {
	if File_workqueue_v1_query_proto != nil {
		return
	}
	file_workqueue_v1_workqueue_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workqueue_v1_query_proto_rawDesc), len(file_workqueue_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workqueue_v1_query_proto_goTypes,
		DependencyIndexes: file_workqueue_v1_query_proto_depIdxs,
		MessageInfos:      file_workqueue_v1_query_proto_msgTypes,
	}.Build()
	File_workqueue_v1_query_proto = out.File
	file_workqueue_v1_query_proto_goTypes = nil
	file_workqueue_v1_query_proto_depIdxs = nil
}
