// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: workqueue/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Work_FullMethodName           = "/pickle.workqueue.v1.Query/Work"
	Query_PendingWork_FullMethodName    = "/pickle.workqueue.v1.Query/PendingWork"
	Query_ValidatorStats_FullMethodName = "/pickle.workqueue.v1.Query/ValidatorStats"
	Query_TotalStats_FullMethodName     = "/pickle.workqueue.v1.Query/TotalStats"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC querier service
type QueryClient interface {
	// Work queries for a specific work unit
	Work(ctx context.Context, in *QueryWorkRequest, opts ...grpc.CallOption) (*QueryWorkResponse, error)
	// PendingWork queries for pending work units
	PendingWork(ctx context.Context, in *QueryPendingWorkRequest, opts ...grpc.CallOption) (*QueryPendingWorkResponse, error)
	// ValidatorStats queries statistics for a validator
	ValidatorStats(ctx context.Context, in *QueryValidatorStatsRequest, opts ...grpc.CallOption) (*QueryValidatorStatsResponse, error)
	// TotalStats queries total statistics
	TotalStats(ctx context.Context, in *QueryTotalStatsRequest, opts ...grpc.CallOption) (*QueryTotalStatsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Work(ctx context.Context, in *QueryWorkRequest, opts ...grpc.CallOption) (*QueryWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryWorkResponse)
	err := c.cc.Invoke(ctx, Query_Work_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingWork(ctx context.Context, in *QueryPendingWorkRequest, opts ...grpc.CallOption) (*QueryPendingWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPendingWorkResponse)
	err := c.cc.Invoke(ctx, Query_PendingWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ValidatorStats(ctx context.Context, in *QueryValidatorStatsRequest, opts ...grpc.CallOption) (*QueryValidatorStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryValidatorStatsResponse)
	err := c.cc.Invoke(ctx, Query_ValidatorStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TotalStats(ctx context.Context, in *QueryTotalStatsRequest, opts ...grpc.CallOption) (*QueryTotalStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTotalStatsResponse)
	err := c.cc.Invoke(ctx, Query_TotalStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC querier service
type QueryServer interface {
	// Work queries for a specific work unit
	Work(context.Context, *QueryWorkRequest) (*QueryWorkResponse, error)
	// PendingWork queries for pending work units
	PendingWork(context.Context, *QueryPendingWorkRequest) (*QueryPendingWorkResponse, error)
	// ValidatorStats queries statistics for a validator
	ValidatorStats(context.Context, *QueryValidatorStatsRequest) (*QueryValidatorStatsResponse, error)
	// TotalStats queries total statistics
	TotalStats(context.Context, *QueryTotalStatsRequest) (*QueryTotalStatsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Work(context.Context, *QueryWorkRequest) (*QueryWorkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Work not implemented")
}
func (UnimplementedQueryServer) PendingWork(context.Context, *QueryPendingWorkRequest) (*QueryPendingWorkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PendingWork not implemented")
}
func (UnimplementedQueryServer) ValidatorStats(context.Context, *QueryValidatorStatsRequest) (*QueryValidatorStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatorStats not implemented")
}
func (UnimplementedQueryServer) TotalStats(context.Context, *QueryTotalStatsRequest) (*QueryTotalStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TotalStats not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Work_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Work(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Work_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Work(ctx, req.(*QueryWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PendingWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingWork(ctx, req.(*QueryPendingWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ValidatorStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidatorStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ValidatorStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidatorStats(ctx, req.(*QueryValidatorStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TotalStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTotalStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TotalStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_TotalStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TotalStats(ctx, req.(*QueryTotalStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pickle.workqueue.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Work",
			Handler:    _Query_Work_Handler,
		},
		{
			MethodName: "PendingWork",
			Handler:    _Query_PendingWork_Handler,
		},
		{
			MethodName: "ValidatorStats",
			Handler:    _Query_ValidatorStats_Handler,
		},
		{
			MethodName: "TotalStats",
			Handler:    _Query_TotalStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workqueue/v1/query.proto",
}
