// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: workqueue/v1/tx.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgSubmitWork submits a new work unit for validation
type MsgSubmitWork struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Submitter is the address submitting the work
	Submitter string `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	// WorkType is the type of work (crypto, supply_chain, ml_data)
	WorkType string `protobuf:"bytes,2,opt,name=work_type,json=workType,proto3" json:"work_type,omitempty"`
	// WorkData is the raw data to validate
	WorkData []byte `protobuf:"bytes,3,opt,name=work_data,json=workData,proto3" json:"work_data,omitempty"`
	// WorkID is a unique identifier (optional, generated if not provided)
	WorkId        string `protobuf:"bytes,4,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitWork) Reset() {
	*x = MsgSubmitWork{}
	mi := &file_workqueue_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitWork) ProtoMessage() {}

func (x *MsgSubmitWork) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitWork.ProtoReflect.Descriptor instead.
func (*MsgSubmitWork) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgSubmitWork) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *MsgSubmitWork) GetWorkType() string {
	if x != nil {
		return x.WorkType
	}
	return ""
}

func (x *MsgSubmitWork) GetWorkData() []byte {
	if x != nil {
		return x.WorkData
	}
	return nil
}

func (x *MsgSubmitWork) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

// MsgSubmitWorkResponse is the response to SubmitWork
type MsgSubmitWorkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WorkID is the ID of the submitted work
	WorkId        string `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitWorkResponse) Reset() {
	*x = MsgSubmitWorkResponse{}
	mi := &file_workqueue_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitWorkResponse) ProtoMessage() {}

func (x *MsgSubmitWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitWorkResponse.ProtoReflect.Descriptor instead.
func (*MsgSubmitWorkResponse) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgSubmitWorkResponse) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

// MsgValidateWork submits a validation result for a work unit
type MsgValidateWork struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Validator is the address of the validator
	Validator string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	// WorkID is the ID of the work unit being validated
	WorkId string `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	// Valid indicates if the work unit passed validation
	Valid bool `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	// Confidence is the validator's confidence in this result (0-100)
	Confidence uint32 `protobuf:"varint,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Proof is optional proof of validation (e.g., hash of verification)
	Proof string `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	// Reason is an optional explanation if invalid
	Reason        string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgValidateWork) Reset() {
	*x = MsgValidateWork{}
	mi := &file_workqueue_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgValidateWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgValidateWork) ProtoMessage() {}

func (x *MsgValidateWork) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgValidateWork.ProtoReflect.Descriptor instead.
func (*MsgValidateWork) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgValidateWork) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *MsgValidateWork) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *MsgValidateWork) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *MsgValidateWork) GetConfidence() uint32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *MsgValidateWork) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

func (x *MsgValidateWork) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// MsgValidateWorkResponse is the response to ValidateWork
type MsgValidateWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgValidateWorkResponse) Reset() {
	*x = MsgValidateWorkResponse{}
	mi := &file_workqueue_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgValidateWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgValidateWorkResponse) ProtoMessage() {}

func (x *MsgValidateWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgValidateWorkResponse.ProtoReflect.Descriptor instead.
func (*MsgValidateWorkResponse) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_tx_proto_rawDescGZIP(), []int{3}
}

// MsgRejectWork explicitly rejects a work unit
type MsgRejectWork struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Validator is the address of the validator
	Validator string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	// WorkID is the ID of the work unit being rejected
	WorkId string `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	// Reason is the reason for rejection
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRejectWork) Reset() {
	*x = MsgRejectWork{}
	mi := &file_workqueue_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRejectWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRejectWork) ProtoMessage() {}

func (x *MsgRejectWork) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRejectWork.ProtoReflect.Descriptor instead.
func (*MsgRejectWork) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgRejectWork) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *MsgRejectWork) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *MsgRejectWork) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// MsgRejectWorkResponse is the response to RejectWork
type MsgRejectWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRejectWorkResponse) Reset() {
	*x = MsgRejectWorkResponse{}
	mi := &file_workqueue_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRejectWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRejectWorkResponse) ProtoMessage() {}

func (x *MsgRejectWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRejectWorkResponse.ProtoReflect.Descriptor instead.
func (*MsgRejectWorkResponse) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_tx_proto_rawDescGZIP(), []int{5}
}

var File_workqueue_v1_tx_proto protoreflect.FileDescriptor

const file_workqueue_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x15workqueue/v1/tx.proto\x12\x13pickle.workqueue.v1\"\x80\x01\n" +
	"\rMsgSubmitWork\x12\x1c\n" +
	"\tsubmitter\x18\x01 \x01(\tR\tsubmitter\x12\x1b\n" +
	"\twork_type\x18\x02 \x01(\tR\bworkType\x12\x1b\n" +
	"\twork_data\x18\x03 \x01(\fR\bworkData\x12\x17\n" +
	"\awork_id\x18\x04 \x01(\tR\x06workId\"0\n" +
	"\x15MsgSubmitWorkResponse\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\"\xac\x01\n" +
	"\x0fMsgValidateWork\x12\x1c\n" +
	"\tvalidator\x18\x01 \x01(\tR\tvalidator\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\rR\n" +
	"confidence\x12\x14\n" +
	"\x05proof\x18\x05 \x01(\tR\x05proof\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\x19\n" +
	"\x17MsgValidateWorkResponse\"^\n" +
	"\rMsgRejectWork\x12\x1c\n" +
	"\tvalidator\x18\x01 \x01(\tR\tvalidator\x12\x17\n" +
	"\awork_id\x18\x02 \x01(\tR\x06workId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x17\n" +
	"\x15MsgRejectWorkResponse2\xa5\x02\n" +
	"\x03Msg\x12\\\n" +
	"\n" +
	"SubmitWork\x12\".pickle.workqueue.v1.MsgSubmitWork\x1a*.pickle.workqueue.v1.MsgSubmitWorkResponse\x12b\n" +
	"\fValidateWork\x12$.pickle.workqueue.v1.MsgValidateWork\x1a,.pickle.workqueue.v1.MsgValidateWorkResponse\x12\\\n" +
	"\n" +
	"RejectWork\x12\".pickle.workqueue.v1.MsgRejectWork\x1a*.pickle.workqueue.v1.MsgRejectWorkResponseB-Z+github.com/maco144/pickle/x/workqueue/typesb\x06proto3"

var (
	file_workqueue_v1_tx_proto_rawDescOnce sync.Once
	file_workqueue_v1_tx_proto_rawDescData []byte
)

func file_workqueue_v1_tx_proto_rawDescGZIP() []byte {
	file_workqueue_v1_tx_proto_rawDescOnce.Do(func() {
		file_workqueue_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workqueue_v1_tx_proto_rawDesc), len(file_workqueue_v1_tx_proto_rawDesc)))
	})
	return file_workqueue_v1_tx_proto_rawDescData
}

var file_workqueue_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_workqueue_v1_tx_proto_goTypes = []any{
	(*MsgSubmitWork)(nil),           // 0: pickle.workqueue.v1.MsgSubmitWork
	(*MsgSubmitWorkResponse)(nil),   // 1: pickle.workqueue.v1.MsgSubmitWorkResponse
	(*MsgValidateWork)(nil),         // 2: pickle.workqueue.v1.MsgValidateWork
	(*MsgValidateWorkResponse)(nil), // 3: pickle.workqueue.v1.MsgValidateWorkResponse
	(*MsgRejectWork)(nil),           // 4: pickle.workqueue.v1.MsgRejectWork
	(*MsgRejectWorkResponse)(nil),   // 5: pickle.workqueue.v1.MsgRejectWorkResponse
}
var file_workqueue_v1_tx_proto_depIdxs = []int32{
	0, // 0: pickle.workqueue.v1.Msg.SubmitWork:input_type -> pickle.workqueue.v1.MsgSubmitWork
	2, // 1: pickle.workqueue.v1.Msg.ValidateWork:input_type -> pickle.workqueue.v1.MsgValidateWork
	4, // 2: pickle.workqueue.v1.Msg.RejectWork:input_type -> pickle.workqueue.v1.MsgRejectWork
	1, // 3: pickle.workqueue.v1.Msg.SubmitWork:output_type -> pickle.workqueue.v1.MsgSubmitWorkResponse
	3, // 4: pickle.workqueue.v1.Msg.ValidateWork:output_type -> pickle.workqueue.v1.MsgValidateWorkResponse
	5, // 5: pickle.workqueue.v1.Msg.RejectWork:output_type -> pickle.workqueue.v1.MsgRejectWorkResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workqueue_v1_tx_proto_init() }
func file_workqueue_v1_tx_proto_init() {
	if File_workqueue_v1_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workqueue_v1_tx_proto_rawDesc), len(file_workqueue_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workqueue_v1_tx_proto_goTypes,
		DependencyIndexes: file_workqueue_v1_tx_proto_depIdxs,
		MessageInfos:      file_workqueue_v1_tx_proto_msgTypes,
	}.Build()
	File_workqueue_v1_tx_proto = out.File
	file_workqueue_v1_tx_proto_goTypes = nil
	file_workqueue_v1_tx_proto_depIdxs = nil
}
