// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: workqueue/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_SubmitWork_FullMethodName   = "/pickle.workqueue.v1.Msg/SubmitWork"
	Msg_ValidateWork_FullMethodName = "/pickle.workqueue.v1.Msg/ValidateWork"
	Msg_RejectWork_FullMethodName   = "/pickle.workqueue.v1.Msg/RejectWork"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the workqueue Msg service
type MsgClient interface {
	// SubmitWork submits a new work unit for validation
	SubmitWork(ctx context.Context, in *MsgSubmitWork, opts ...grpc.CallOption) (*MsgSubmitWorkResponse, error)
	// ValidateWork submits a validation result for a work unit
	ValidateWork(ctx context.Context, in *MsgValidateWork, opts ...grpc.CallOption) (*MsgValidateWorkResponse, error)
	// RejectWork explicitly rejects a work unit
	RejectWork(ctx context.Context, in *MsgRejectWork, opts ...grpc.CallOption) (*MsgRejectWorkResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitWork(ctx context.Context, in *MsgSubmitWork, opts ...grpc.CallOption) (*MsgSubmitWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSubmitWorkResponse)
	err := c.cc.Invoke(ctx, Msg_SubmitWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ValidateWork(ctx context.Context, in *MsgValidateWork, opts ...grpc.CallOption) (*MsgValidateWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgValidateWorkResponse)
	err := c.cc.Invoke(ctx, Msg_ValidateWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RejectWork(ctx context.Context, in *MsgRejectWork, opts ...grpc.CallOption) (*MsgRejectWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRejectWorkResponse)
	err := c.cc.Invoke(ctx, Msg_RejectWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the workqueue Msg service
type MsgServer interface {
	// SubmitWork submits a new work unit for validation
	SubmitWork(context.Context, *MsgSubmitWork) (*MsgSubmitWorkResponse, error)
	// ValidateWork submits a validation result for a work unit
	ValidateWork(context.Context, *MsgValidateWork) (*MsgValidateWorkResponse, error)
	// RejectWork explicitly rejects a work unit
	RejectWork(context.Context, *MsgRejectWork) (*MsgRejectWorkResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) SubmitWork(context.Context, *MsgSubmitWork) (*MsgSubmitWorkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitWork not implemented")
}
func (UnimplementedMsgServer) ValidateWork(context.Context, *MsgValidateWork) (*MsgValidateWorkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateWork not implemented")
}
func (UnimplementedMsgServer) RejectWork(context.Context, *MsgRejectWork) (*MsgRejectWorkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectWork not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_SubmitWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitWork)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SubmitWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitWork(ctx, req.(*MsgSubmitWork))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ValidateWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgValidateWork)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ValidateWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ValidateWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ValidateWork(ctx, req.(*MsgValidateWork))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RejectWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRejectWork)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RejectWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RejectWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RejectWork(ctx, req.(*MsgRejectWork))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pickle.workqueue.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitWork",
			Handler:    _Msg_SubmitWork_Handler,
		},
		{
			MethodName: "ValidateWork",
			Handler:    _Msg_ValidateWork_Handler,
		},
		{
			MethodName: "RejectWork",
			Handler:    _Msg_RejectWork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workqueue/v1/tx.proto",
}
