// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: workqueue/v1/workqueue.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkUnit represents a single unit of work to be validated
type WorkUnit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is a unique identifier for this work unit
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type is the type of work (crypto, supply_chain, ml_data)
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Data is the raw data that needs to be validated
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// SubmittedAt is the block height when the work was submitted
	SubmittedAt int64 `protobuf:"varint,4,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	// ValidatedAt is the block height when the work was validated
	ValidatedAt int64 `protobuf:"varint,5,opt,name=validated_at,json=validatedAt,proto3" json:"validated_at,omitempty"`
	// Validator is the address of the validator that handled this work
	Validator string `protobuf:"bytes,6,opt,name=validator,proto3" json:"validator,omitempty"`
	// Status is the current status of the work
	Status string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	// Confidence is the validator's confidence in the result (0-100)
	Confidence uint32 `protobuf:"varint,8,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Proof is optional proof of validation
	Proof         string `protobuf:"bytes,9,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkUnit) Reset() {
	*x = WorkUnit{}
	mi := &file_workqueue_v1_workqueue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkUnit) ProtoMessage() {}

func (x *WorkUnit) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_workqueue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkUnit.ProtoReflect.Descriptor instead.
func (*WorkUnit) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_workqueue_proto_rawDescGZIP(), []int{0}
}

func (x *WorkUnit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkUnit) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkUnit) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WorkUnit) GetSubmittedAt() int64 {
	if x != nil {
		return x.SubmittedAt
	}
	return 0
}

func (x *WorkUnit) GetValidatedAt() int64 {
	if x != nil {
		return x.ValidatedAt
	}
	return 0
}

func (x *WorkUnit) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *WorkUnit) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkUnit) GetConfidence() uint32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *WorkUnit) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

// ValidatorStats tracks performance metrics for a validator
type ValidatorStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address is the validator's address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// TotalWorkValidated is the number of work units validated
	TotalWorkValidated uint64 `protobuf:"varint,2,opt,name=total_work_validated,json=totalWorkValidated,proto3" json:"total_work_validated,omitempty"`
	// TotalWorkRejected is the number of work units rejected
	TotalWorkRejected uint64 `protobuf:"varint,3,opt,name=total_work_rejected,json=totalWorkRejected,proto3" json:"total_work_rejected,omitempty"`
	// Specializations tracks count of work per type
	Specializations map[string]uint64 `protobuf:"bytes,4,rep,name=specializations,proto3" json:"specializations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// AverageConfidence is the average confidence of validations
	AverageConfidence uint32 `protobuf:"varint,5,opt,name=average_confidence,json=averageConfidence,proto3" json:"average_confidence,omitempty"`
	// LastActiveAt is the block height when last active
	LastActiveAt  int64 `protobuf:"varint,6,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorStats) Reset() {
	*x = ValidatorStats{}
	mi := &file_workqueue_v1_workqueue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorStats) ProtoMessage() {}

func (x *ValidatorStats) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_workqueue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorStats.ProtoReflect.Descriptor instead.
func (*ValidatorStats) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_workqueue_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatorStats) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ValidatorStats) GetTotalWorkValidated() uint64 {
	if x != nil {
		return x.TotalWorkValidated
	}
	return 0
}

func (x *ValidatorStats) GetTotalWorkRejected() uint64 {
	if x != nil {
		return x.TotalWorkRejected
	}
	return 0
}

func (x *ValidatorStats) GetSpecializations() map[string]uint64 {
	if x != nil {
		return x.Specializations
	}
	return nil
}

func (x *ValidatorStats) GetAverageConfidence() uint32 {
	if x != nil {
		return x.AverageConfidence
	}
	return 0
}

func (x *ValidatorStats) GetLastActiveAt() int64 {
	if x != nil {
		return x.LastActiveAt
	}
	return 0
}

// WorkQueue stores the queue of work units
type WorkQueue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PendingWork is a list of work units waiting to be validated
	PendingWork []*WorkUnit `protobuf:"bytes,1,rep,name=pending_work,json=pendingWork,proto3" json:"pending_work,omitempty"`
	// TotalSubmitted is the total number of work units ever submitted
	TotalSubmitted uint64 `protobuf:"varint,2,opt,name=total_submitted,json=totalSubmitted,proto3" json:"total_submitted,omitempty"`
	// TotalValidated is the total number of work units validated
	TotalValidated uint64 `protobuf:"varint,3,opt,name=total_validated,json=totalValidated,proto3" json:"total_validated,omitempty"`
	// TotalRejected is the total number of work units rejected
	TotalRejected uint64 `protobuf:"varint,4,opt,name=total_rejected,json=totalRejected,proto3" json:"total_rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkQueue) Reset() {
	*x = WorkQueue{}
	mi := &file_workqueue_v1_workqueue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkQueue) ProtoMessage() {}

func (x *WorkQueue) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_workqueue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkQueue.ProtoReflect.Descriptor instead.
func (*WorkQueue) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_workqueue_proto_rawDescGZIP(), []int{2}
}

func (x *WorkQueue) GetPendingWork() []*WorkUnit {
	if x != nil {
		return x.PendingWork
	}
	return nil
}

func (x *WorkQueue) GetTotalSubmitted() uint64 {
	if x != nil {
		return x.TotalSubmitted
	}
	return 0
}

func (x *WorkQueue) GetTotalValidated() uint64 {
	if x != nil {
		return x.TotalValidated
	}
	return 0
}

func (x *WorkQueue) GetTotalRejected() uint64 {
	if x != nil {
		return x.TotalRejected
	}
	return 0
}

// GenesisState defines the initial state of the workqueue module
type GenesisState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WorkQueue is the initial work queue state
	WorkQueue *WorkQueue `protobuf:"bytes,1,opt,name=work_queue,json=workQueue,proto3" json:"work_queue,omitempty"`
	// Validators is the list of initial validators with their stats
	Validators    []*ValidatorStats `protobuf:"bytes,2,rep,name=validators,proto3" json:"validators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_workqueue_v1_workqueue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_workqueue_v1_workqueue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_workqueue_v1_workqueue_proto_rawDescGZIP(), []int{3}
}

func (x *GenesisState) GetWorkQueue() *WorkQueue {
	if x != nil {
		return x.WorkQueue
	}
	return nil
}

func (x *GenesisState) GetValidators() []*ValidatorStats {
	if x != nil {
		return x.Validators
	}
	return nil
}

var File_workqueue_v1_workqueue_proto protoreflect.FileDescriptor

const file_workqueue_v1_workqueue_proto_rawDesc = "" +
	"\n" +
	"\x1cworkqueue/v1/workqueue.proto\x12\x13pickle.workqueue.v1\"\xf4\x01\n" +
	"\bWorkUnit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12!\n" +
	"\fsubmitted_at\x18\x04 \x01(\x03R\vsubmittedAt\x12!\n" +
	"\fvalidated_at\x18\x05 \x01(\x03R\vvalidatedAt\x12\x1c\n" +
	"\tvalidator\x18\x06 \x01(\tR\tvalidator\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"confidence\x18\b \x01(\rR\n" +
	"confidence\x12\x14\n" +
	"\x05proof\x18\t \x01(\tR\x05proof\"\x89\x03\n" +
	"\x0eValidatorStats\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x120\n" +
	"\x14total_work_validated\x18\x02 \x01(\x04R\x12totalWorkValidated\x12.\n" +
	"\x13total_work_rejected\x18\x03 \x01(\x04R\x11totalWorkRejected\x12b\n" +
	"\x0fspecializations\x18\x04 \x03(\v28.pickle.workqueue.v1.ValidatorStats.SpecializationsEntryR\x0fspecializations\x12-\n" +
	"\x12average_confidence\x18\x05 \x01(\rR\x11averageConfidence\x12$\n" +
	"\x0elast_active_at\x18\x06 \x01(\x03R\flastActiveAt\x1aB\n" +
	"\x14SpecializationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xc6\x01\n" +
	"\tWorkQueue\x12@\n" +
	"\fpending_work\x18\x01 \x03(\v2\x1d.pickle.workqueue.v1.WorkUnitR\vpendingWork\x12'\n" +
	"\x0ftotal_submitted\x18\x02 \x01(\x04R\x0etotalSubmitted\x12'\n" +
	"\x0ftotal_validated\x18\x03 \x01(\x04R\x0etotalValidated\x12%\n" +
	"\x0etotal_rejected\x18\x04 \x01(\x04R\rtotalRejected\"\x92\x01\n" +
	"\fGenesisState\x12=\n" +
	"\n" +
	"work_queue\x18\x01 \x01(\v2\x1e.pickle.workqueue.v1.WorkQueueR\tworkQueue\x12C\n" +
	"\n" +
	"validators\x18\x02 \x03(\v2#.pickle.workqueue.v1.ValidatorStatsR\n" +
	"validatorsB-Z+github.com/maco144/pickle/x/workqueue/typesb\x06proto3"

var (
	file_workqueue_v1_workqueue_proto_rawDescOnce sync.Once
	file_workqueue_v1_workqueue_proto_rawDescData []byte
)

func file_workqueue_v1_workqueue_proto_rawDescGZIP() []byte {
	file_workqueue_v1_workqueue_proto_rawDescOnce.Do(func() {
		file_workqueue_v1_workqueue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workqueue_v1_workqueue_proto_rawDesc), len(file_workqueue_v1_workqueue_proto_rawDesc)))
	})
	return file_workqueue_v1_workqueue_proto_rawDescData
}

var file_workqueue_v1_workqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_workqueue_v1_workqueue_proto_goTypes = []any{
	(*WorkUnit)(nil),       // 0: pickle.workqueue.v1.WorkUnit
	(*ValidatorStats)(nil), // 1: pickle.workqueue.v1.ValidatorStats
	(*WorkQueue)(nil),      // 2: pickle.workqueue.v1.WorkQueue
	(*GenesisState)(nil),   // 3: pickle.workqueue.v1.GenesisState
	nil,                    // 4: pickle.workqueue.v1.ValidatorStats.SpecializationsEntry
}
var file_workqueue_v1_workqueue_proto_depIdxs = []int32{
	4, // 0: pickle.workqueue.v1.ValidatorStats.specializations:type_name -> pickle.workqueue.v1.ValidatorStats.SpecializationsEntry
	0, // 1: pickle.workqueue.v1.WorkQueue.pending_work:type_name -> pickle.workqueue.v1.WorkUnit
	2, // 2: pickle.workqueue.v1.GenesisState.work_queue:type_name -> pickle.workqueue.v1.WorkQueue
	1, // 3: pickle.workqueue.v1.GenesisState.validators:type_name -> pickle.workqueue.v1.ValidatorStats
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_workqueue_v1_workqueue_proto_init() }
func file_workqueue_v1_workqueue_proto_init() {
	if File_workqueue_v1_workqueue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workqueue_v1_workqueue_proto_rawDesc), len(file_workqueue_v1_workqueue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workqueue_v1_workqueue_proto_goTypes,
		DependencyIndexes: file_workqueue_v1_workqueue_proto_depIdxs,
		MessageInfos:      file_workqueue_v1_workqueue_proto_msgTypes,
	}.Build()
	File_workqueue_v1_workqueue_proto = out.File
	file_workqueue_v1_workqueue_proto_goTypes = nil
	file_workqueue_v1_workqueue_proto_depIdxs = nil
}
